name: Deploy Pages
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Build Angular (production)
        run: npx ng build --configuration production

      - name: Add 404.html for SPA routing
        run: cp dist/ml-portfolio/browser/index.html dist/ml-portfolio/browser/404.html

      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: dist/ml-portfolio/browser

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: site

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
