name: CI & Deploy Pages

on:
  push:
    branches: [main, "feature/**"]
  pull_request:
    branches: [main, "feature/**"]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci
      - run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci
      - run: npm run build:prod
      - run: |
          cp dist/ml-portfolio/browser/index.html dist/ml-portfolio/browser/404.html
          echo 'maximilian-lamm.de' > dist/ml-portfolio/browser/CNAME
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: dist/ml-portfolio/browser
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: site
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/ml-portfolio/browser
