name: Deploy Pages

on:
  workflow_run:
    workflows: ["Lint & Test"]
    types: [completed]

permissions:
  contents: write

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci
      - run: npm run build:prod
      - run: |
          cp dist/ml-portfolio/browser/index.html dist/ml-portfolio/browser/404.html
          echo 'maximilian-lamm.de' > dist/ml-portfolio/browser/CNAME
          mkdir -p dist/ml-portfolio/browser/ml-portfolio
          cat > dist/ml-portfolio/browser/ml-portfolio/index.html <<'EOF'
          <!doctype html><meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=/" />
          <script>location.replace('/');</script>
          EOF
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: dist/ml-portfolio/browser
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: site
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          keep_files: false
          force_orphan: true
