name: Lint & Test

on:
  push:
    branches: [main, "feature/**"]
  pull_request:
    branches: [main, "feature/**"]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm run test
